### ISSUE TITLE
能否让界面全屏显示？

### ISSUE THREAD

**Issue by laidingq** [coolzilj/ComfyUI-Photopea#2]
大佬您好，这个界面能否全面显示，目前这样操作显得有些局促。
非常好的工具，感谢大佬制作comfyui插件

**Comment by laidingq** [comment]
是的，默认可以目前这个大小，如果能通过按钮全屏占满浏览器最好，操作会更方便一些

**Comment by coolzilj** [comment]
加了切换全屏的按钮，更新插件试试看，配合 F11 使用效果更好

**Comment by laidingq** [comment]
试了，完美，特别感谢

**Comment by kenic123** [comment]
全屏不管用

**Comment by coolzilj** [comment]
> 全屏不管用

是不是装了某些装饰主题的插件？
