### ISSUE TITLE
It conflicts with a plugin named AIGODLIKE-ComfyUI-Studio, and fails to display the save and fullscreen buttons when installed at the same time.

### ISSUE THREAD

**Issue by kenic123** [coolzilj/ComfyUI-Photopea#4]
After I tested it, I found that：It conflicts with a plugin named AIGODLIKE-ComfyUI-Studio, and fails to display the save and fullscreen buttons when installed at the same time.I'm lost because that's the plugin I had to use too。

**Comment by coolzilj** [comment]
hmm, see what i can do.

**Comment by coolzilj** [comment]
fix, plz update to latest.
